var PRODUCTS = [
  {id:1, name:"BedBox con Patas", cat:"bedbox", catL:"BedBox",
   img:"assets/img/Bedbox.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Mejora la calidad de tu descanso con el soporte BedBox®. Estructura de acero y madera con cubierta acolchada. Prolonga la vida útil de tu colchón y mejora tu experiencia de descanso.",
   specs:["Estructura de acero y madera","Cubierta acolchada de tela","Patas de acero con niveladoras","6 medidas disponibles","IVA (16%) incluido"],
   variants:[
     {l:"Individual 78×188 cm", p:150},
     {l:"Individual 98×188 cm", p:154},
     {l:"Individual 98×198 cm", p:161},
     {l:"Matrimonial 138×188 cm", p:226},
     {l:"Queen 158×188 cm", p:276},
     {l:"King 200×200 cm", p:363}
   ]},
  {id:2, name:"Litera Sevilla", cat:"litera", catL:"Litera",
   img:"assets/img/litera-sevilla.jpg",
   note:"No incluye colchón · REF · IVA (16%)",
   desc:"Litera clásica con dos camas de acero sólido. Baranda de seguridad superior y escalera lateral integrada. Ideal para habitaciones infantiles y juveniles.",
   specs:["2 camas superpuestas","Baranda de seguridad superior","Escalera lateral integrada","Acero estructural de alta resistencia","No incluye colchón"],
   variants:[{l:"Plaza (estándar)", p:400}]},
  {id:3, name:"Litera Segovia", cat:"litera", catL:"Litera",
   img:"assets/img/litera-segovia.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Litera compacta y resistente con acabado anticorrosivo. Excelente relación calidad-precio para maximizar el espacio.",
   specs:["Acero calibre 16","Baranda de seguridad","Diseño compacto","Fácil de armar","Acabado anticorrosivo"],
   variants:[{l:"Plaza (estándar)", p:300}]},
  {id:4, name:"Cama Canguro", cat:"cama", catL:"Cama",
   img:"assets/img/cama-canguro.jpg",
   note:"No incluye colchón · REF · IVA (16%)",
   desc:"Cama con segunda cama extraíble inferior sobre ruedas. Perfecta para espacios reducidos o alojar visitas. No incluye colchón.",
   specs:["Cama secundaria extraíble","Ruedas de deslizamiento silencioso","Estructura doble de acero","No incluye colchón"],
   variants:[{l:"Plaza (estándar)", p:287}]},
  {id:5, name:"Litera Extrafirme", cat:"litera", catL:"Litera",
   img:"assets/img/litera-extrafirme.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Acero calibre 14 con soldadura MIG de alta resistencia. Diseñada para uso intensivo con máxima exigencia estructural.",
   specs:["Acero calibre 14 reforzado","Soldadura MIG","Baranda perimetral de seguridad","Capacidad aumentada por nivel"],
   variants:[{l:"Plaza (estándar)", p:320}]},
  {id:6, name:"Litera Institucional", cat:"litera", catL:"Litera",
   img:"assets/img/litera-institucional.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Para hoteles, internados y cuarteles. Pintura epóxica resistente y durabilidad extrema para entornos de alta rotación.",
   specs:["Uso comercial e institucional","Pintura epóxica","Sin aristas peligrosas","Acero estructural pesado"],
   variants:[{l:"Plaza (estándar)", p:218}]},
  {id:7, name:"Cama Modena", cat:"cama", catL:"Cama",
   img:"assets/img/cama-modena.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Diseño minimalista con estructura sólida de acero. Comodidad y seguridad a precio accesible con los estándares de calidad FAVECA.",
   specs:["Estructura sólida de acero","Diseño minimalista","Cabecero integrado","Pintura electrostática"],
   variants:[
     {l:"Individual 1.00×1.90 m", p:140},
     {l:"Matrimonial 1.40×1.90 m", p:210}
   ]},
  {id:8, name:"Cama Victoria", cat:"cama", catL:"Cama",
   img:"assets/img/cama-victoria.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Elegante respaldo curvado con estructura sólida de acero. Diseño clásico y funcionalidad con los estándares de calidad FAVECA.",
   specs:["Respaldo curvado elegante","Estructura de acero","Acabado anticorrosivo","Soportes de somier integrados"],
   variants:[
     {l:"Individual 0.80×1.90 m", p:162},
     {l:"Individual 1.00×1.90 m", p:187},
     {l:"Matrimonial 1.40×1.90 m", p:268}
   ]},
  {id:9, name:"Cama Sandwich", cat:"cama", catL:"Cama",
   img:"assets/img/cama-sandwich.jpg",
   note:"REF · IVA incluido (16%)",
   desc:"Doble capa de acero para rigidez excepcional y sistema anti-ruido integrado. La opción más robusta de toda la línea FAVECA.",
   specs:["Doble capa de acero","Sistema anti-ruido integrado","Rigidez estructural superior","Pintura electrostática duradera"],
   variants:[{l:"Plaza (estándar)", p:187}]}
];

// Nuevo producto
PRODUCTS.push({
  id:10, name:"Puff Cama", cat:"cama", catL:"Cama",
  img:"assets/img/puff-cama.jpg",
  note:"REF · IVA incluido (16%)",
  desc:"En FAVECA hemos llevado la sencillez al siguiente nivel al crear una cama que es mucho más que eso. Nuestra cama innovadora se convierte en un cómodo puff, ofreciéndote una solución versátil y funcional. Descubre la comodidad y la versatilidad en un solo mueble. Tu espacio se verá deslumbrante y aprovechado al máximo.",
  specs:["2 en 1: puff y cama","Estructura de acero resistente","Tapizado acolchado incluido","Diseño compacto y versátil","Fácil transformación","IVA (16%) incluido"],
  variants:[{l:"Plaza (estándar)", p:287}]
});
